apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        livenessProbe:
          tcpSocket:
            port: 21
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21000
        - containerPort: 21001
        - containerPort: 21002
        - containerPort: 21003
        - containerPort: 21004
        - containerPort: 21005
---

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps-service
  labels:
    app: ftps
spec:
  type: LoadBalancer
  ports:
  - name: port-20
    port: 20
    targetPort: 20
  - name: port-21
    port: 21
    targetPort: 21
  - name: port-21000
    port: 21000
    targetPort: 21000
  - name: port-21001
    port: 21001
    targetPort: 21001
  - name: port-21002
    port: 21002
    targetPort: 21002
  - name: port-21003
    port: 21003
    targetPort: 21003
  - name: port-21004
    port: 21004
    targetPort: 21004
  - name: port-21005
    port: 21005
    targetPort: 21005
  selector:
    app: ftps


